name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo build --release
      - run: cargo test --release
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- --deny warnings
